### ISSUE TITLE
Updation of pre-releases as releases in github

### ISSUE THREAD

**Issue by kishaningithub** [jeroenrinzema/psql-wire#18]
As you can see in the below screenshot and link the releases are tagged as "pre-release". Can you kindly publish them as a release?

Link: https://github.com/jeroenrinzema/psql-wire/releases

### Screenshot
<img width="800" alt="Screenshot 2022-10-09 at 9 46 11 PM" src="https://user-images.githubusercontent.com/763760/194767731-fcd3c7b2-c415-41d7-863a-c9a38f60c0a8.png">

**Comment by jeroenrinzema** [comment]
Hi @kishaningithub, thanks for pointing this out. I will update the release tags.

**Comment by jeroenrinzema** [comment]
The releases have been updated. Closing this ticket for now.
