### ISSUE TITLE
Handling of "prepared statement already exists" error

### ISSUE THREAD

**Issue by kishaningithub** [jeroenrinzema/psql-wire#40]
At times the client of the psql server gets the error "prepared statement already exists". I dont have a exact simulation steps as such because the issue is intermittent. 

During the times this happens, i see the server returns the above error first and then the SimpleQueryHandler gets called.

### Screenshot from pgcli client

<img width="325" alt="Screenshot 2022-11-01 at 10 48 41 PM" src="https://user-images.githubusercontent.com/763760/199295961-716570b7-85a8-404e-a8bb-7c4ca463ecb4.png">

**Comment by jeroenrinzema** [comment]
Hi @kishaningithub, thanks for reporting this issue. I suspect that prepared statements are not flushed properly and cause this error to be thrown. I will try to recreate the bug and try to resolve the issue.

**Comment by jeroenrinzema** [comment]
@kishaningithub I have just adjusted the prepared statements cache to not throw an error if a prepared statement already exists but to override it instead. Would you be able to try to reproduce the error? Feel free to Reopen the issue if the issue persists.

**Comment by kishaningithub** [comment]
@jeroenrinzema Thanks for the fix and sorry for my late response. Now the "prepared statement already exists" is gone but i get the error `got no result from the query` even though the query actually wrote a result set (screenshot below)

Should i raise a separate issue or should this be reopened?

### Screenshot 1
<img width="353" alt="Screenshot 2022-11-19 at 5 22 30 PM" src="https://user-images.githubusercontent.com/763760/202849431-e62d49df-a7c8-4a53-a9fa-af628147998e.png">

One interesting thing here is that if i fire the same query very fast i actually get the result "at times" (Screenshot below)

### Screenshot 2
<img width="423" alt="Screenshot 2022-11-19 at 5 24 26 PM" src="https://user-images.githubusercontent.com/763760/202849524-cfd0cec1-cafe-4401-bd63-3e77cf8b098e.png">

Something wierd is going on.

## Logs when the error happens

```json
{"level":"debug","timestamp":"2022-11-19T17:25:48.402488+05:30","caller":"psql-wire@v0.4.1-0.20221115092616-2480a4e5fc17/command.go:67","msg":"incoming command","length":944,"type":"P"}
{"level":"debug","timestamp":"2022-11-19T17:25:48.402723+05:30","caller":"psql-wire@v0.4.1-0.20221115092616-2480a4e5fc17/command.go:276","msg":"incoming extended query","query":"SELECT n.nspname as \"Schema\",\n                    c.relname as \"Name\",\n                    CASE c.relkind\n                      WHEN 'r' THEN 'table' WHEN 'v' THEN 'view'\n                      WHEN 'p' THEN 'partitioned table'\n                      WHEN 'm' THEN 'materialized view' WHEN 'i' THEN 'index'\n                      WHEN 'S' THEN 'sequence' WHEN 's' THEN 'special'\n                      WHEN 'f' THEN 'foreign table' END\n                    as \"Type\",\n                    pg_catalog.pg_get_userbyid(c.relowner) as \"Owner\"\n          \n            FROM    pg_catalog.pg_class c\n                    LEFT JOIN pg_catalog.pg_namespace n\n                      ON n.oid = c.relnamespace\n            WHERE   c.relkind = ANY($1) \n            AND n.nspname <> 'pg_catalog'\n            AND n.nspname <> 'information_schema'\n            AND n.nspname !~ '^pg_toast'\n            AND pg_catalog.pg_table_is_visible(c.oid)  ORDER BY 1, 2","name":"","parameters":1}
{"level":"debug","timestamp":"2022-11-19T17:25:48.402844+05:30","caller":"psql-wire@v0.4.1-0.20221115092616-2480a4e5fc17/command.go:67","msg":"incoming command","length":36,"type":"B"}
{"level":"debug","timestamp":"2022-11-19T17:25:48.40287+05:30","caller":"psql-wire@v0.4.1-0.20221115092616-2480a4e5fc17/command.go:344","msg":"reading parameters format codes","length":1}
{"level":"debug","timestamp":"2022-11-19T17:25:48.402902+05:30","caller":"psql-wire@v0.4.1-0.20221115092616-2480a4e5fc17/command.go:372","msg":"reading parameters values","length":1}
{"level":"debug","timestamp":"2022-11-19T17:25:48.402913+05:30","caller":"psql-wire@v0.4.1-0.20221115092616-2480a4e5fc17/command.go:386","msg":"incoming parameter","value":"{r,p,v,m,S,f,\"\"}"}
{"level":"debug","timestamp":"2022-11-19T17:25:48.402923+05:30","caller":"psql-wire@v0.4.1-0.20221115092616-2480a4e5fc17/command.go:397","msg":"reading result-column format codes","length":1}
{"level":"debug","timestamp":"2022-11-19T17:25:48.402958+05:30","caller":"psql-wire@v0.4.1-0.20221115092616-2480a4e5fc17/command.go:67","msg":"incoming command","length":6,"type":"D"}
{"level":"debug","timestamp":"2022-11-19T17:25:48.402977+05:30","caller":"psql-wire@v0.4.1-0.20221115092616-2480a4e5fc17/command.go:67","msg":"incoming command","length":9,"type":"E"}
{"level":"debug","timestamp":"2022-11-19T17:25:48.402986+05:30","caller":"psql-wire@v0.4.1-0.20221115092616-2480a4e5fc17/command.go:435","msg":"executing","name":"","limit":0}
{"level":"debug","timestamp":"2022-11-19T17:25:49.791743+05:30","caller":"psql-wire@v0.4.1-0.20221115092616-2480a4e5fc17/command.go:67","msg":"incoming command","length":4,"type":"S"}
```
