### ISSUE TITLE
Fishy behaviours when handling request from multiple connections

### ISSUE THREAD

**Issue by kishaningithub** [jeroenrinzema/psql-wire#49]
## Way to simulate
- Add a test which starts the psql wire server
- Add mulltiple sub tests which sends sql queries
- Example: https://github.com/kishaningithub/rdapp/blob/refactor-interaction-service/componenttest/rdapp_test.go

## Observed behavior
- When running the sub test individually the tests pass
- When run as a whole (i.e. run the parent test) then we see wierdness where the following classes of errors happen
   - The psql wire server returns response to the client before the simple query handler finishes its work
   - Argument mismatch error

**Comment by jeroenrinzema** [comment]
Hi @kishaningithub, thanks for reporting this! Is it possible for you to recreate this issue inside a UNIT test within this repo and open a PR? This way we could fix this issue and include some additional tests in order to improve the extended query protocol support.

**Comment by kishaningithub** [comment]
Thanks for the motivation @jeroenrinzema Have now raised a PR which is able to simulate the exact errors which i got https://github.com/jeroenrinzema/psql-wire/pull/50

**Comment by jeroenrinzema** [comment]
Thanks! I have opened a PR containing a fix for the issue #51 and included some additional details inside your PR to why this issue occurred https://github.com/jeroenrinzema/psql-wire/pull/50#issuecomment-1365898717
